// Generated by CoffeeScript 1.6.3
(function() {
  var async, debug, fs, getFeatureList, inspect, knownOpts, nopt, parsedArgs, path, shortHands;

  fs = require('fs');

  path = require('path');

  inspect = require('util').inspect;

  async = require('async');

  nopt = require('nopt');

  debug = require('debug')('lake-list');

  getFeatureList = require('./file-locator').getFeatureList;

  knownOpts = {
    help: Boolean
  };

  shortHands = {
    h: ['--help']
  };

  parsedArgs = nopt(knownOpts, shortHands, process.argv, 2);

  if (parsedArgs.help) {
    console.log('USAGE');
    console.log(inspect(knownOpts));
    console.log(inspect(shortHands));
    process.exit(0);
  }

  getFeatureList(function(err, list) {
    var l, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      l = list[_i];
      _results.push(console.log(l));
    }
    return _results;
  });

}).call(this);
